server:
  port: 9090

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${CITY_CARD_POSTGRE_USERNAME}
    password: ${CITY_CARD_POSTGRE_PASSWORD}
    url: ${CITY_CARD_POSTGRE_URL}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

city-card:
  jwt:
    secret-key: ${CITY_CARD_JWT_SECRETKEY}
    issuer: ${CITY_CARD_JWT_ISSUER}